  - name: Install MYSQL librabries
    ansible.builtin.pip:
      name: "{{ item }}"
    loop:
    - cryptography
    - pyMySQL

  - name: Install MYSQL server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enabled mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.sdaws82s.online
    register: mysql_info
    ignore_errors: true

  - name: print the output
    debug:
      msg: "Mysql info: {{ mysql_info }}"

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"    
    when: mysql_info.failed is true
    